BTC:
    priceUnit:
        - INR
    decimalPlace:
        - 0
    updateFreq: 60
    discordBotKey: ODI3NjEwMDczNDA3ODE1Njkw.YGdh8Q.-y72fd9GM49_nkqhwV1e0zKl0rE
    guildId: 379896554271670273

ETH:
    priceUnit:
        - USD
    decimalPlace:
        - 2
        - 5
    updateFreq: 60
    discordBotKey: ODI3NjEwMDczNDA3ODE1Njkw.YGdh8Q.-y72fd9GM49_nkqhwV1e0zKl0rE
    guildId: 379896554271670273

YFI:
    priceUnit:
        - INR
    decimalPlace:
        - 0
        - 2
    updateFreq: 120
    discordBotKey: ODI3NjEwMDczNDA3ODE1Njkw.YGdh8Q.-y72fd9GM49_nkqhwV1e0zKl0rE
    guildId: 379896554271670273
